-- SQL que funciona tanto no PostgreSQL (Neon) quanto no H2 usado na sua máquina e nos testes.

create table usuario (
    id         bigint generated by default as identity primary key,
    nome       varchar(80)  not null,
    email      varchar(160) not null unique,
    -- Nunca a senha em si: só o resultado do BCrypt.
    senha_hash varchar(100) not null,
    criado_em  timestamp with time zone not null
);

-- Quem está logado. Guarda o SHA-256 do token, para que um vazamento do banco não entregue sessões prontas.
create table sessao (
    token_hash varchar(64) primary key,
    usuario_id bigint not null references usuario (id) on delete cascade,
    expira_em  timestamp with time zone not null
);

create table quiz (
    id          bigint generated by default as identity primary key,
    -- Parte final do link de compartilhamento.
    codigo      varchar(12)  not null unique,
    autor_id    bigint       not null references usuario (id),
    titulo      varchar(120) not null,
    descricao   varchar(500),
    tema        varchar(40),
    -- Público aparece em "Explorar"; os demais só abrem por link.
    publico     boolean      not null,
    criado_em   timestamp with time zone not null,
    -- Excluir só esconde o quiz: quem já respondeu continua vendo o próprio resultado.
    excluido_em timestamp with time zone
);

create table questao (
    id         bigint generated by default as identity primary key,
    quiz_id    bigint        not null references quiz (id) on delete cascade,
    ordem      integer       not null,
    tipo       varchar(20)   not null,
    enunciado  varchar(1000) not null,
    explicacao varchar(1000)
);

-- Em questões de verdadeiro ou falso cada linha é uma afirmação, e "correta" diz se ela é verdadeira.
create table alternativa (
    id         bigint generated by default as identity primary key,
    questao_id bigint       not null references questao (id) on delete cascade,
    ordem      integer      not null,
    texto      varchar(500) not null,
    correta    boolean      not null
);

create table tentativa (
    id         bigint generated by default as identity primary key,
    quiz_id    bigint        not null references quiz (id),
    usuario_id bigint        not null references usuario (id),
    pontos     numeric(7, 2) not null,
    total      integer       not null,
    feita_em   timestamp with time zone not null
);

-- O que a pessoa marcou. Escolha: uma linha por alternativa marcada. Verdadeiro ou falso: uma linha por
-- afirmação julgada, com valor = true para "verdadeiro".
create table resposta (
    tentativa_id   bigint  not null references tentativa (id) on delete cascade,
    alternativa_id bigint  not null references alternativa (id),
    valor          boolean not null,
    primary key (tentativa_id, alternativa_id)
);

create index quiz_autor_idx on quiz (autor_id);
create index questao_quiz_idx on questao (quiz_id);
create index alternativa_questao_idx on alternativa (questao_id);
create index tentativa_quiz_idx on tentativa (quiz_id);
create index tentativa_usuario_idx on tentativa (usuario_id);
create index sessao_usuario_idx on sessao (usuario_id);
